/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as BooksIndexRouteImport } from './routes/books/index'
import { Route as BooksBookNumberRouteImport } from './routes/books/$bookNumber'
import { Route as GemsNewRouteImport } from './routes/gems.new'
import { Route as ListsNewRouteImport } from './routes/lists.new'
import { Route as ApiOSplatRouteImport } from './routes/api.o.$'
import { Route as ApiSSplatRouteImport } from './routes/api/s/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookNumberRoute = BooksBookNumberRouteImport.update({
  id: '/books/$bookNumber',
  path: '/books/$bookNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const GemsNewRoute = GemsNewRouteImport.update({
  id: '/gems/new',
  path: '/gems/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsNewRoute = ListsNewRouteImport.update({
  id: '/lists/new',
  path: '/lists/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOSplatRoute = ApiOSplatRouteImport.update({
  id: '/api/o/$',
  path: '/api/o/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSSplatRoute = ApiSSplatRouteImport.update({
  id: '/api/s/$',
  path: '/api/s/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/books/$bookNumber': typeof BooksBookNumberRoute
  '/gems/new': typeof GemsNewRoute
  '/lists/new': typeof ListsNewRoute
  '/books/': typeof BooksIndexRoute
  '/api/o/$': typeof ApiOSplatRoute
  '/api/s/$': typeof ApiSSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/books/$bookNumber': typeof BooksBookNumberRoute
  '/gems/new': typeof GemsNewRoute
  '/lists/new': typeof ListsNewRoute
  '/books': typeof BooksIndexRoute
  '/api/o/$': typeof ApiOSplatRoute
  '/api/s/$': typeof ApiSSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/books/$bookNumber': typeof BooksBookNumberRoute
  '/gems/new': typeof GemsNewRoute
  '/lists/new': typeof ListsNewRoute
  '/books/': typeof BooksIndexRoute
  '/api/o/$': typeof ApiOSplatRoute
  '/api/s/$': typeof ApiSSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/books/$bookNumber'
    | '/gems/new'
    | '/lists/new'
    | '/books/'
    | '/api/o/$'
    | '/api/s/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/books/$bookNumber'
    | '/gems/new'
    | '/lists/new'
    | '/books'
    | '/api/o/$'
    | '/api/s/$'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/books/$bookNumber'
    | '/gems/new'
    | '/lists/new'
    | '/books/'
    | '/api/o/$'
    | '/api/s/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  BooksBookNumberRoute: typeof BooksBookNumberRoute
  GemsNewRoute: typeof GemsNewRoute
  ListsNewRoute: typeof ListsNewRoute
  BooksIndexRoute: typeof BooksIndexRoute
  ApiOSplatRoute: typeof ApiOSplatRoute
  ApiSSplatRoute: typeof ApiSSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookNumber': {
      id: '/books/$bookNumber'
      path: '/books/$bookNumber'
      fullPath: '/books/$bookNumber'
      preLoaderRoute: typeof BooksBookNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gems/new': {
      id: '/gems/new'
      path: '/gems/new'
      fullPath: '/gems/new'
      preLoaderRoute: typeof GemsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/new': {
      id: '/lists/new'
      path: '/lists/new'
      fullPath: '/lists/new'
      preLoaderRoute: typeof ListsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/o/$': {
      id: '/api/o/$'
      path: '/api/o/$'
      fullPath: '/api/o/$'
      preLoaderRoute: typeof ApiOSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/s/$': {
      id: '/api/s/$'
      path: '/api/s/$'
      fullPath: '/api/s/$'
      preLoaderRoute: typeof ApiSSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  BooksBookNumberRoute: BooksBookNumberRoute,
  GemsNewRoute: GemsNewRoute,
  ListsNewRoute: ListsNewRoute,
  BooksIndexRoute: BooksIndexRoute,
  ApiOSplatRoute: ApiOSplatRoute,
  ApiSSplatRoute: ApiSSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
